name: Deploy Application To Prod

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

    - name: Ensure Publish Directory Exists
      run: mkdir -p ./publish

    - name: Download from Blob Storage
      run: |
        az storage blob download \
          --name ${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --file ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --account-name ${{ vars.AZURE_ARTIFACT_ACCOUNT_NAME }} \
          --container-name ${{ vars.AZURE_ARTIFACT_CONTAINER_NAME }} \
          --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }}

    - name: Deploy to Azure Webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.PROD_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PROD_WEBAPP_PUBLISHPROFILE }}
        package: ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip

    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        inlineScript: az logout

  ping-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-prod

    steps:
      - name: Get version
        id: get_version
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Ping Health Check URL
        uses: GarageGroup/platform-ping-app@v0.0.3
        with:
          health_check_url: https://${{ vars.PROD_APIM_DNS }}/health/${{ vars.APIM_HEALTH_NAME }}?subscription-key=${{ secrets.PROD_APIM_SUBKEY }}
          contains: ${{ steps.get_version.outputs.version }}
          retry_delay_in_seconds: 15
          max_attempts: 10

  update-swagger-test:
    runs-on: ubuntu-latest
    needs: ping-prod

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_WEB_APP }}

    - name: Update API Management Specification
      run: |
        az apim api import --resource-group ${{ vars.PROD_APIM_RESOURCE_GROUP }} \
          --specification-format "OpenApi" \
          --service-name ${{ vars.PROD_APIM_NAME }} \
          --api-id ${{ vars.APIM_WEB_API_ID }} \
          --path ${{ vars.APIM_WEB_API_PATH }} \
          --service-url https://${{ vars.PROD_WEBAPP_NAME }}.azurewebsites.net/ \
          --subscription-required false \
          --specification-url https://${{ vars.PROD_APIM_DNS }}/swagger/${{ vars.APIM_SWAGGER_NAME }}/swagger.json?subscription-key=${{ secrets.PROD_APIM_SUBKEY }}
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS_WEB_APP }}

    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        inlineScript: az logout